"use strict";
//  Conditional Test:
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
let Fruit = 'Mango';
console.log("is Fruit == 'Mango'?. I predict True.");
console.log(Fruit == 'Mango');
let color = 'white';
console.log(" color == 'white'. I predict True");
console.log(color == 'white');
let myWeight = '59';
console.log("myWeight == '59'. I predict True");
console.log(myWeight == '59');
let favoriteFood = "Pizza";
console.log("favoriteFood == 'Pizza'. I predict True");
console.log(favoriteFood == 'Pizza');
let mobile = "Iphone";
console.log("mobile == 'Iphone'. I predict True");
console.log(mobile == 'Iphone');
let bike = "honda";
console.log("bike == 'honda'. I predict False");
console.log(bike == 'honda');
let iceCream = "Chocoalte";
console.log("iceCream == 'Chocolate'. I predict False");
console.log(iceCream == 'Chocolate');
let bag = "Gucci";
console.log("bag == 'Gucci'. I predict False");
console.log(bag == 'Gucci');
let Myname = "Duaa";
console.log("Myname == 'Duaa'. I predict False");
console.log(Myname == 'Duaa');
let BestFriend;
console.log("BestFriend == 'Komal'. I predict False");
console.log(BestFriend == 'Komal');
